# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10.16

    working_directory: ~/pinion

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: "Running Tests"
          environment:
            CI_API_PORT: 5001
          command: |
            mkdir -p reports/ava
            yarn lint
            yarn test:ci
      - store_test_results:
          path: reports
      - store_artifacts:
          path: reports

workflows:
  version: 2
  commit:
    jobs:
      - test

